name: Build and Upload to Artifactory

on:
  release:
    types: [released]

env:
  JFROG_URL: https://demo.jfrog.io/artifactory
  APPLICATION_NAME: test-library


jobs:
  pushToICR:
    name: Push to Artifactory
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set Up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: "corretto"
        java-version: 17

    - name: Get branch name
      id: branchName
      run: echo ::set-output name=short_ref::${GITHUB_REF#refs/*/}

    - name: Set branch name
      run: echo "BRANCH_NAME=`echo ${{ steps.branchName.outputs.short_ref }} | sed -E 's/[\/\\\:]+/-/g'`" >> $GITHUB_ENV

    - name: Get latest release tag
      run: echo "RELEASE_TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%dT%H:%M:%S')"

    - name: Setup JFrog CLI
      uses: jfrog/setup-jfrog-cli@v4
      with:
        version: 4.1.3

    - name: Configure JFrog CLI
      run: |
          jfrog rt config --url=$JFROG_URL --user=${{ secrets.ARTIFACTORY_CRED_USR }} --access-token=${{ secrets.ARTIFACTORY_CRED_PAT }} --interactive=false
          jfrog rt c show
      env:
          JFROG_URL: https://demo.jfrog.io/artifactory
          JFROG_CLI_OFFER_CONFIG: false

    - name: Publish to JFrog Artifactory
      run: |
          ./gradlew build
          jfrog rt u build/libs/  test-library/${{ env.RELEASE_TAG }}/
      env:
        ARTIFACTORY_CRED_USR: ${{ secrets.ARTIFACTORY_CRED_USR }}
        ARTIFACTORY_CRED_PAT: ${{ secrets.ARTIFACTORY_CRED_PAT }}
